name: "Podcast Generator"
author: "Ray Villalobos"
description: "Generate a podcast feed from a YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  color: "git-branch"
  icon: "red"
inputs:
  email:
    description: "The computer's email address"
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: "The committer's name"
    required: true
    default: ${{ github.actor }}